import { useState } from 'react';
import useSWR from 'swr';
import { fetcher } from '../services/api';
const labels:Record<string,string>={submitting:'Submission unresolved',accepted:'Accepted by EMR',uncertain:'Outcome unknown',rejected:'Rejected or not submitted',duplicate_blocked:'Duplicate blocked locally'};
export default function CampaignInvitationHistory({admin=false}:{admin?:boolean}) {
  const [page,setPage]=useState(1);const [status,setStatus]=useState('');
  const {data,error,isLoading,mutate}=useSWR<{data:{total:number;pages:number;attempts:Array<{id:string;campaignName:string;locationName:string;businessName?:string;recipient:string;status:string;detail:string;providerReference?:string;providerStatus?:number;createdAt:string}>}}>(`${admin?'/admin/campaign-invitations':'/campaigns/history'}?page=${page}${status?'&status='+status:''}`,fetcher);
  return <section className="rounded-xl bg-white p-5 shadow-card space-y-4"><h2 className="text-lg font-semibold">Invitation request history</h2>
    <p className="text-sm text-slate-600">EMR sends the messages. Acceptance is not proof of delivery: opt-outs, duplicate rules and send windows can affect processing. This history covers requests made through SuperLocalSEO after this feature was released.</p>
    <details className="text-sm"><summary className="cursor-pointer font-medium">How to investigate an invitation</summary><div className="mt-3 space-y-2 text-slate-600"><p>For accepted requests, allow for the campaign send window. Delivery cannot be confirmed from the invitation response alone.</p><p>For an unknown or unresolved submission, do not resend. An operator must inspect the correct business and campaign in EMR, matching the recipient, time and available provider reference. If the outcome remains unclear, escalate to vendor support. Refreshing this history does not query delivery or resend anything.</p><p>Rejected requests need their cause corrected before a deliberate new request. Local duplicate protection blocks recent accepted requests for 14 days and unresolved requests indefinitely. It does not override EMR opt-outs or prove that a recipient received a message.</p></div></details>
    <div className="flex flex-wrap gap-3 items-center text-sm"><label>Status <select aria-label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="rounded border-slate-300"><option value="">All statuses</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button onClick={()=>void mutate()} className="underline">Refresh request history</button></div>
    {error&&<p role="alert">Unable to load history. Refresh to retry.</p>}{isLoading&&<p role="status">Loading request history…</p>}
    {!error&&!isLoading&&data?.data.total===0&&<p className="text-sm text-slate-500">No recorded invitation requests match this filter.</p>}
    {data?.data.attempts.map(a=><article key={a.id} className="border-t border-slate-200 pt-3 text-sm space-y-1"><h3 className="font-medium">{admin&&a.businessName?`${a.businessName} · `:''}{a.campaignName} · {a.locationName}</h3><p>{a.recipient} · {labels[a.status]??a.status}</p><p className="text-slate-600">{a.detail}</p><p className="text-xs text-slate-500">{new Date(a.createdAt).toLocaleString()} · Request {a.id}</p>{admin&&<p className="text-xs text-slate-500">Provider reference: {a.providerReference??'Not supplied'} · HTTP response: {a.providerStatus??'Not observed'}</p>}</article>)}
    {(data?.data.pages??0)>1&&<div className="flex gap-4 text-sm"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous requests</button><span>Page {page} of {data?.data.pages}</span><button disabled={page>=(data?.data.pages??0)} onClick={()=>setPage(p=>p+1)}>Next requests</button></div>}
  </section>;
}
