import { Router } from 'express';
import healthRouter from './health';
import authRouter from './auth';
import clientsRouter from './clients';
import locationsRouter from './locations';
import keywordsRouter from './keywords';
import integrationsRouter from './integrations';
import rankingsRouter from './rankings';
import citationsRouter from './citations';
import reviewsRouter from './reviews';
import metricsRouter from './metrics';
import billingRouter from './billing';
import reportsRouter from './reports';
import analyticsRouter from './analytics';
import auditRouter from './audit';
import teamRouter from './team';
import widgetRouter from './widget';
import campaignsRouter from './campaigns';
import competitorsRouter from './competitors';
import qrRouter from './qr';
import auditsBlRouter from './audits_bl';
import reputationRouter from './reputation';
import geoGridRouter from './geogrid';

const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/clients', clientsRouter);
router.use('/locations', locationsRouter);
router.use('/keywords', keywordsRouter);
router.use('/integrations', integrationsRouter);
router.use('/rankings', rankingsRouter);
router.use('/citations', citationsRouter);
router.use('/reviews', reviewsRouter);
router.use('/metrics', metricsRouter);
router.use('/billing', billingRouter);
router.use('/reports', reportsRouter);
router.use('/analytics', analyticsRouter);
router.use('/audit', auditRouter);
router.use('/team', teamRouter);
router.use('/widget', widgetRouter);
router.use('/campaigns', campaignsRouter);
router.use('/competitors', competitorsRouter);
router.use('/qr', qrRouter);
router.use('/audits/bl', auditsBlRouter);
router.use('/reputation', reputationRouter);
router.use('/geo-grid', geoGridRouter);

export default router;
