import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, Check, Fan, FileText, MapPin, Menu, MessageCircle, Plug, Search, Sparkles, Star, Wrench, X, Home } from 'lucide-react';
import './Landing.css';

const INTEL_URL = 'https://app.superlocalseo.com/intel-request';
// Public prices mirror docs/PRICING.md. Subscription behavior is unchanged.
const PRICING = { lite: 149, pro: 349, extraLocation: 125 } as const;
const trades = [{ Icon: Fan, name: 'HVAC' }, { Icon: Wrench, name: 'Plumbing' }, { Icon: Plug, name: 'Electrical' }, { Icon: Home, name: 'Roofing' }];

function Wordmark() {
  return <span className="landing-wordmark"><MapPin aria-hidden="true" fill="currentColor" /><span>SuperLocalSEO</span></span>;
}

function SampleReport() {
  return <article className="sample-report" aria-label="Illustrative monthly visibility report for Example HVAC">
    <div className="report-top"><Wordmark /><span className="sample-label">Illustrative sample</span></div>
    <h2>Monthly visibility brief</h2>
    <div className="report-business"><div><strong>Example HVAC</strong><small>123 Main St · Riverton, CO 80501</small></div><div><strong>May 2024</strong><small>Report period<br />Apr 1 – Apr 30, 2024</small></div></div>
    <section className="report-panel"><h3>Google rankings <Search size={17} aria-hidden="true" /></h3>
      <div className="report-chart-row"><div className="report-chart"><div className="chart-key"><span>HVAC services</span><span>AC repair</span><span>Furnace installation</span></div>
        <svg viewBox="0 0 280 90" role="img" aria-label="Illustrative ranking trends improving during April">
          {[15, 35, 55, 75].map(y => <line key={y} x1="18" y1={y} x2="275" y2={y} stroke="#e4e7df" />)}
          <g fontSize="8" fill="#57665e"><text x="1" y="18">1</text><text x="1" y="38">10</text><text x="1" y="58">20</text><text x="1" y="78">50</text></g>
          <polyline points="22,44 40,39 58,41 76,35 94,33 112,29 130,28 148,24 166,26 184,21 202,23 220,17 238,19 256,15 274,14" fill="none" stroke="#176649" strokeWidth="2" />
          <polyline points="22,56 40,53 58,55 76,49 94,50 112,46 130,47 148,44 166,46 184,44 202,47 220,40 238,43 256,33 274,31" fill="none" stroke="#e87938" strokeWidth="2" />
          <polyline points="22,70 40,68 58,65 76,67 94,62 112,65 130,60 148,62 166,57 184,60 202,56 220,58 238,55 256,57 274,56" fill="none" stroke="#a2bfa4" strokeWidth="2" />
        </svg><div className="chart-dates"><span>Apr 1</span><span>Apr 8</span><span>Apr 15</span><span>Apr 22</span><span>Apr 30</span></div>
      </div><div className="report-stat"><strong>12</strong><span>of 25 keywords<br />on page 1</span><small>+3 since last month</small></div></div>
    </section>
    <section className="report-panel"><h3>Review activity <Star size={17} aria-hidden="true" /></h3><div className="report-chart-row"><div className="report-chart"><div className="chart-key"><span>New reviews</span><span>Unanswered</span></div><div className="review-bars" aria-hidden="true">{[16, 23, 35, 20, 54, 28, 16, 38, 49, 31, 67, 39, 48, 27, 22, 15, 30, 51, 70, 25, 42, 19].map((h, i) => <span key={i} style={{ height: `${h}%` }}><i style={{ height: `${i % 3 === 0 ? 50 : 18}%` }} /></span>)}</div><div className="chart-dates"><span>Apr 1</span><span>Apr 8</span><span>Apr 15</span><span>Apr 22</span><span>Apr 30</span></div></div><div className="report-stat"><strong>14</strong><span>new reviews</span><strong className="orange-text">2</strong><span>unanswered</span></div></div></section>
    <section className="report-panel report-ai"><div><h3>AI mentions</h3>{[['ChatGPT', '8 mentions'], ['Gemini', '5 mentions'], ['Perplexity', '3 mentions']].map(([name, count]) => <div className="provider-row" key={name}><Sparkles size={13} aria-hidden="true" /><span>{name}</span><span>{count}</span></div>)}</div><div className="report-recommendation"><span className="recommendation-icon">!</span><div><small>Recommendation</small><strong>Review unanswered customer feedback.</strong><p>Two recent reviews have not been responded to.</p></div></div></section>
    <section className="report-panel"><h3>Service area coverage <span className="pro-label">Pro</span></h3><div className="coverage-row"><div className="coverage-map" role="img" aria-label="Illustrative coverage map around Riverton"><span>Riverton</span><div className="coverage-grid">{Array.from({ length: 25 }, (_, i) => <i key={i} style={{ opacity: 0.2 + ((i * 7) % 9) / 13 }} />)}</div><MapPin size={20} aria-hidden="true" /></div><div className="coverage-legend"><strong>Active coverage</strong><span>Riverton and 6 nearby areas</span><p>● Primary area</p><p>● Nearby areas</p><p>● Additional opportunities</p></div></div></section>
    <p className="report-disclaimer">Sample data for illustrative purposes only. Features vary by plan.</p>
  </article>;
}

export default function Landing() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const reportDialog = useRef<HTMLDialogElement>(null);
  const plans = useRef<HTMLDetailsElement>(null);
  const showReport = () => reportDialog.current?.showModal();
  const showPlans = () => { if (plans.current) { plans.current.open = true; plans.current.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' }); } };

  return <div className="landing-page">
    <a className="landing-skip" href="#main-content">Skip to main content</a>
    <header className="landing-header landing-container"><Link to="/" aria-label="SuperLocalSEO home"><Wordmark /></Link><nav className="desktop-nav" aria-label="Main navigation"><a href="#how-it-works">How it works</a><button onClick={showReport}>Sample report</button><a href="#pricing">Pricing</a><Link to="/login">Sign in</Link></nav><button className="landing-button header-cta" onClick={showReport}>See a sample report</button><span className="brand-promise">Local businesses<br />Stronger tomorrow</span><button className="mobile-toggle" aria-label={mobileMenuOpenOpenLabel(mobileMenuOpen)} aria-expanded={mobileMenuOpen} aria-controls="mobile-navigation" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>{mobileMenuOpen ? <X /> : <Menu />}</button></header>
    {mobileMenuOpen && <nav id="mobile-navigation" className="mobile-navigation" aria-label="Mobile navigation" onKeyDown={e => { if (e.key === 'Escape') setMobileMenuOpen(false); }}><a href="#how-it-works" onClick={() => setMobileMenuOpen(false)}>How it works</a><button onClick={() => { setMobileMenuOpen(false); showReport(); }}>Sample report</button><a href="#pricing" onClick={() => setMobileMenuOpen(false)}>Pricing</a><Link to="/login">Sign in</Link></nav>}
    <main id="main-content">
      <section className="landing-hero landing-container" aria-labelledby="hero-heading"><div className="hero-copy"><p className="landing-eyebrow">Visibility monitoring for home services</p><h1 id="hero-heading">Your online visibility.<br />One clear picture.</h1><p className="hero-description">Google rankings, customer reviews and AI mentions — tracked regularly and summarized every month.</p><div className="hero-actions"><a href={INTEL_URL} className="landing-button">Check my business free <ArrowRight size={21} aria-hidden="true" /></a><button className="landing-text-link" onClick={showReport}>See the monthly report</button></div><p className="hero-note">No card required · Plans from <strong>${PRICING.lite}/month</strong></p><div className="trade-strip"><p>For home service businesses</p><ul>{trades.map(({ Icon, name }) => <li key={name}><Icon aria-hidden="true" strokeWidth={1.4} /><span>{name}</span></li>)}</ul></div></div><div className="hero-report"><div className="report-stack"><SampleReport /></div><p className="report-annotation">A clearer view for<br />what comes next.</p></div></section>
      <section id="how-it-works" className="landing-process" aria-labelledby="process-heading"><div className="landing-container process-grid"><h2 id="process-heading">You run the business.<br />Keep the signals in view.</h2>{[{ n: '01', title: <>Rankings<br />checked daily</>, text: 'We track your positions on Google for the searches that matter in your area.' }, { n: '02', title: <>AI visibility<br />checked weekly</>, text: 'We monitor mentions across leading AI platforms so you can see where your business appears.' }, { n: '03', title: <>Your report<br />delivered monthly</>, text: 'A clear, easy-to-read summary of your online visibility, with practical next steps.' }].map(item => <div className="process-step" key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></div>)}</div></section>
      <section className="landing-owner" aria-labelledby="owner-heading"><div className="owner-photo"><img src="/landing-reference.png" alt="A home service business owner reviewing her laptop in the office" loading="lazy" /></div><div className="owner-copy"><h2 id="owner-heading">Built for the owner.<br />Useful for the office.</h2><ul><li><FileText aria-hidden="true" />Review monitoring in one place.</li><li><MessageCircle aria-hidden="true" />AI-drafted replies you can approve.</li><li><BarChart3 aria-hidden="true" />Clear reports you can revisit.</li></ul></div></section>
      <section id="pricing" className="landing-pricing landing-container" aria-label="Plans and pricing"><div className="price-summary"><h2>Lite</h2><p className="plan-price"><strong>${PRICING.lite}</strong>/month</p><p>Essential visibility monitoring<br />for one location.</p></div><div className="price-action"><h2>No setup fee.</h2><p>Compare plans to see what’s included.</p><button className="landing-button" onClick={showPlans}>Choose your plan</button></div><div className="price-summary"><h2>Pro</h2><p className="plan-price"><strong>${PRICING.pro}</strong>/month</p><p>Expanded tracking and deeper<br />insights for growing businesses.</p></div></section>
      <details className="landing-plan-details landing-container" ref={plans}><summary>Compare Lite and Pro</summary><div className="plan-detail-grid">{(['lite', 'pro'] as const).map(plan => <article key={plan}><h2>{plan === 'lite' ? 'Lite' : 'Pro'} · ${PRICING[plan]}/month</h2><p>{plan === 'lite' ? 'One location. The essentials in one place.' : `One location included. Additional locations $${PRICING.extraLocation}/month each.`}</p><ul>{(plan === 'lite' ? ['Daily Google rank tracking', 'Review monitoring and AI-drafted replies', 'Review request campaigns and website widgets', 'AI visibility verdict', 'Monthly visibility report'] : ['Everything in Lite', 'Detailed AI answers, sources and history', 'Service area visibility maps', 'Weekly directory checks and guided listing cleanup', 'Competitor insights, website audits, team access and exports']).map(feature => <li key={feature}><Check size={17} aria-hidden="true" />{feature}</li>)}</ul><Link className="landing-button" to={`/register?plan=${plan}`}>Start 7-day free trial <ArrowRight size={17} aria-hidden="true" /></Link><small>No credit card required. Choose your paid plan at checkout.</small></article>)}</div></details>
    </main>
    <footer className="landing-footer"><div className="landing-container footer-content"><Link to="/" aria-label="SuperLocalSEO home"><Wordmark /></Link><span className="footer-tagline">Local visibility<br />for real work</span><nav aria-label="Footer navigation"><a href="#how-it-works">How it works</a><button onClick={showReport}>Sample report</button><a href="#pricing">Pricing</a><Link to="/login">Sign in</Link></nav><span className="brand-promise">Stronger<br />local communities</span></div><div className="footer-legal landing-container"><span>© {new Date().getFullYear()} SuperLocalSEO</span><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms of Service</Link><a href="mailto:hello@superlocalseo.com">Contact</a></div><div className="footer-landscape" aria-hidden="true" /></footer>
    <dialog className="landing-report-dialog" ref={reportDialog} aria-label="Sample monthly visibility report" onClick={e => { if (e.target === e.currentTarget) reportDialog.current?.close(); }}><div className="dialog-toolbar"><span>Monthly report preview</span><button autoFocus onClick={() => reportDialog.current?.close()} aria-label="Close sample report"><X /></button></div><SampleReport /><p className="dialog-note">An illustrative design preview, not a customer report. Your report reflects your business data and selected plan.</p></dialog>
  </div>;
}

function mobileMenuOpenOpenLabel(open: boolean) { return open ? 'Close navigation' : 'Open navigation'; }
